FROM python:3.12-slim

RUN apt-get update -qq && apt-get install -qq -y \
    git \
    libosmesa6 \
    libgl1-mesa-dri \
    libglx-mesa0 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir uv

WORKDIR /w
